// ==========================================================================
// NUROVA - MODULE C: 66 UNIQUE AUTHENTIC AYURVEDIC PRODUCTS CATALOGUE
// (EVERY SINGLE PRODUCT HAS A DISTINCT, HIGH-QUALITY PHOTOGRAPH)
// ==========================================================================
const API_BASE_URL = "http://localhost:5000";
export const AYURVEDIC_CATEGORIES = [
  { id: "all", name: "All Remedies", icon: "🌿" },
  { id: "herbal-supplements", name: "Herbal Supplements", icon: "🌱" },
  { id: "oils-ghee", name: "Oils & Ghee", icon: "✨" },
  { id: "teas-infusions", name: "Teas & Infusions", icon: "🍵" },
  { id: "classical-churnas", name: "Classical Vatis & Churnas", icon: "🏺" },
  { id: "natural-skincare", name: "Natural Skincare", icon: "🧴" },
  { id: "hair-scalp", name: "Hair & Scalp Care", icon: "💆" },
  { id: "yoga-meditation", name: "Yoga & Copperware", icon: "🧘" },
  { id: "aromatherapy", name: "Aromatherapy & Dhoop", icon: "💨" },
  { id: "wellness-kits", name: "Panchakarma & Gift Sets", icon: "🎁" }
];

export const DOSHA_TYPES = [
  { id: "all", label: "All Doshas" },
  { id: "vata", label: "Vata (Air & Space)", color: "vata" },
  { id: "pitta", label: "Pitta (Fire & Water)", color: "pitta" },
  { id: "kapha", label: "Kapha (Earth & Water)", color: "kapha" },
  { id: "tridoshic", label: "Tridoshic (All Three)", color: "tridoshic" }
];

export const AYURVEDIC_BENEFITS = [
  "Immunity Boost",
  "Stress & Sleep",
  "Digestion & Gut",
  "Skin Glow & Hair",
  "Energy & Vitality",
  "Joint & Muscle Care"
];

export const productsData = [
  // =========================================================================
  // 1. HERBAL SUPPLEMENTS & RASAYANAS (10 Unique Products)
  // =========================================================================
  {
    id: 1,
    name: "Pure Ashwagandha KSM-66 Root Extract",
    category: "herbal-supplements",
    categoryLabel: "Herbal Supplements",
    price: 499,
    originalPrice: 649,
    rating: 4.9,
    reviewCount: 142,
    dosha: "vata",
    doshaLabel: "Vata Balancing",
    benefits: ["Stress & Sleep", "Energy & Vitality"],
    organic: true,
    inStock: true,
    stockCount: 38,
    icon: "🌿",
    image: "https://images.unsplash.com/photo-1615485290382-441e4d049cb5?auto=format&fit=crop&w=600&q=80",
    description: "Full-spectrum root extract promoting deep cellular vitality, healthy cortisol levels, and peaceful rest.",
    ingredients: ["Organic Ashwagandha (Withania Somnifera)", "BioPerine Black Pepper Extract"],
    dosage: "Take 1 capsule twice daily with warm milk or water after meals.",
    certifications: ["100% USDA Organic", "GMP Certified", "AYUSH Approved"]
  },
  {
    id: 2,
    name: "Triphala Organic Colon & Gut Detox",
    category: "herbal-supplements",
    categoryLabel: "Herbal Supplements",
    price: 349,
    originalPrice: 450,
    rating: 4.8,
    reviewCount: 98,
    dosha: "tridoshic",
    doshaLabel: "Tridoshic Harmony",
    benefits: ["Digestion & Gut", "Immunity Boost"],
    organic: true,
    inStock: true,
    stockCount: 50,
    icon: "🫐",
    image: "https://images.unsplash.com/photo-1540420773420-3366772f4999?auto=format&fit=crop&w=600&q=80",
    description: "Classic three-fruit blend (Amalaki, Bibhitaki, Haritaki) for gentle colon cleansing, gut microbiome, and digestion.",
    ingredients: ["Organic Amalaki", "Organic Bibhitaki", "Organic Haritaki"],
    dosage: "1 teaspoon at bedtime in warm water or honey.",
    certifications: ["Non-GMO", "Vegan", "Eco-Harvested"]
  },
  {
    id: 3,
    name: "Brahmi Mind Clarity & Medhya Rasayana",
    category: "herbal-supplements",
    categoryLabel: "Herbal Supplements",
    price: 429,
    originalPrice: 550,
    rating: 4.8,
    reviewCount: 76,
    dosha: "pitta",
    doshaLabel: "Pitta Cooling",
    benefits: ["Stress & Sleep", "Energy & Vitality"],
    organic: true,
    inStock: true,
    stockCount: 30,
    icon: "🧠",
    image: "https://images.unsplash.com/photo-1509316975850-ff9c5deb0cd9?auto=format&fit=crop&w=600&q=80",
    description: "Potent Medhya Rasayana drops to sharpen focus, soothe mental fatigue, and promote mindful calm.",
    ingredients: ["Bacopa Monnieri (Brahmi)", "Shankhpushpi", "Gotu Kola"],
    dosage: "10-15 drops in water twice daily.",
    certifications: ["GMP Certified", "Heavy Metal Tested"]
  },
  {
    id: 4,
    name: "Shatavari Hormone & Vitality Nectar",
    category: "herbal-supplements",
    categoryLabel: "Herbal Supplements",
    price: 449,
    originalPrice: 599,
    rating: 4.8,
    reviewCount: 89,
    dosha: "pitta",
    doshaLabel: "Pitta Balancing",
    benefits: ["Energy & Vitality", "Immunity Boost"],
    organic: true,
    inStock: true,
    stockCount: 35,
    icon: "🌸",
    image: "https://images.unsplash.com/photo-1512069772995-ec65ed45afd6?auto=format&fit=crop&w=600&q=80",
    description: "Queen of herbs (Asparagus Racemosus) nourishing female reproductive health, hormonal balance, and vitality.",
    ingredients: ["Organic Shatavari Root Powder", "Pravahak Herbs"],
    dosage: "1 teaspoon morning and evening in warm milk.",
    certifications: ["Organic Wildcrafted", "GMP Certified"]
  },
  {
    id: 5,
    name: "Shilajit Pure Himalayan Gold Resin (20g)",
    category: "herbal-supplements",
    categoryLabel: "Herbal Supplements",
    price: 1299,
    originalPrice: 1699,
    rating: 5.0,
    reviewCount: 320,
    dosha: "kapha",
    doshaLabel: "Kapha & Vata Rejuvenation",
    benefits: ["Energy & Vitality", "Immunity Boost"],
    organic: true,
    inStock: true,
    stockCount: 20,
    icon: "🏔️",
    image: "https://images.unsplash.com/photo-1546868871-7041f2a55e12?auto=format&fit=crop&w=600&q=80",
    description: "Sun-purified Grade A Himalayan Shilajit rich in 80+ trace minerals and 75% fulvic acid for stamina.",
    ingredients: ["100% Pure Himalayan Black Shilajit Resin"],
    dosage: "Pea-sized portion dissolved in lukewarm milk or green tea.",
    certifications: ["Lab Tested", "Heavy Metal Free", "AYUSH Approved"]
  },
  {
    id: 6,
    name: "Gokshura Strength & Stamina Tablets",
    category: "herbal-supplements",
    categoryLabel: "Herbal Supplements",
    price: 399,
    originalPrice: 499,
    rating: 4.7,
    reviewCount: 65,
    dosha: "vata",
    doshaLabel: "Vata & Pitta Support",
    benefits: ["Energy & Vitality"],
    organic: true,
    inStock: true,
    stockCount: 45,
    icon: "⚡",
    image: "https://images.unsplash.com/photo-1550572017-edd951aa8f72?auto=format&fit=crop&w=600&q=80",
    description: "Traditional Tribulus Terrestris extract supporting muscle recovery, kidney filtration, and vigor.",
    ingredients: ["Pure Gokshura Extract", "Pippali"],
    dosage: "1 tablet twice daily after meals.",
    certifications: ["GMP Certified", "100% Herbal"]
  },
  {
    id: 7,
    name: "Wild Amalaki Natural Vitamin C Rasayana",
    category: "herbal-supplements",
    categoryLabel: "Herbal Supplements",
    price: 329,
    originalPrice: 420,
    rating: 4.8,
    reviewCount: 110,
    dosha: "tridoshic",
    doshaLabel: "Tridoshic Immune Shield",
    benefits: ["Immunity Boost", "Skin Glow & Hair"],
    organic: true,
    inStock: true,
    stockCount: 60,
    icon: "🍋",
    image: "https://images.unsplash.com/photo-1576678927484-cc907957088c?auto=format&fit=crop&w=600&q=80",
    description: "Forest-harvested Indian Gooseberry concentrated for antioxidant defense, glowing skin, and digestion.",
    ingredients: ["Wild Organic Indian Gooseberry (Emblica Officinalis)"],
    dosage: "1-2 tablets daily with morning hydration.",
    certifications: ["USDA Organic", "Zero Fillers"]
  },
  {
    id: 8,
    name: "Neem Blood Purifier & Skin Clear Vati",
    category: "herbal-supplements",
    categoryLabel: "Herbal Supplements",
    price: 299,
    originalPrice: 380,
    rating: 4.7,
    reviewCount: 88,
    dosha: "pitta",
    doshaLabel: "Pitta & Kapha Cleansing",
    benefits: ["Skin Glow & Hair", "Immunity Boost"],
    organic: true,
    inStock: true,
    stockCount: 55,
    icon: "🍃",
    image: "https://images.unsplash.com/photo-1508746829417-e6f548d8d6ed?auto=format&fit=crop&w=600&q=80",
    description: "Deep systemic blood purification targeting stubborn acne, skin inflammation, and liver toxicity.",
    ingredients: ["Organic Neem Leaf Extract", "Neem Bark", "Manjistha"],
    dosage: "1 tablet with water twice daily.",
    certifications: ["AYUSH Approved", "Toxin Free"]
  },
  {
    id: 9,
    name: "Guduchi / Giloy Immuno-Protective Drops",
    category: "herbal-supplements",
    categoryLabel: "Herbal Supplements",
    price: 279,
    originalPrice: 350,
    rating: 4.9,
    reviewCount: 154,
    dosha: "tridoshic",
    doshaLabel: "Amrit Rasayana (All Doshas)",
    benefits: ["Immunity Boost", "Digestion & Gut"],
    organic: true,
    inStock: true,
    stockCount: 70,
    icon: "💧",
    image: "https://images.unsplash.com/photo-1608571423902-eed4a5ad8108?auto=format&fit=crop&w=600&q=80",
    description: "Known as 'Amrita' (divine nectar), Giloy stem extract stimulates immune leukocytes and wards off seasonal bugs.",
    ingredients: ["Tinospora Cordifolia (Giloy) Aqueous Extract"],
    dosage: "10-20 drops in 50ml warm water before breakfast.",
    certifications: ["Doctor Formulated", "100% Pure"]
  },
  {
    id: 10,
    name: "Arjuna Heart & Cardio Tonic Capsules",
    category: "herbal-supplements",
    categoryLabel: "Herbal Supplements",
    price: 389,
    originalPrice: 499,
    rating: 4.8,
    reviewCount: 72,
    dosha: "pitta",
    doshaLabel: "Pitta & Kapha Heart Care",
    benefits: ["Energy & Vitality"],
    organic: true,
    inStock: true,
    stockCount: 30,
    icon: "❤️",
    image: "https://images.unsplash.com/photo-1587854692152-cbe660dbde88?auto=format&fit=crop&w=600&q=80",
    description: "Terminalia Arjuna bark extract nourishing healthy circulation, vascular tone, and cardiovascular stamina.",
    ingredients: ["Arjuna Bark Extract (Standardized Tannins)"],
    dosage: "1 capsule twice daily with meals.",
    certifications: ["GMP Certified", "Clinically Validated"]
  },

  // =========================================================================
  // 2. AYURVEDIC OILS & GHEE (8 Unique Products)
  // =========================================================================
  {
    id: 11,
    name: "Artisanal A2 Gir Cow Vedic Bilona Ghee (500ml)",
    category: "oils-ghee",
    categoryLabel: "Oils & Ghee",
    price: 799,
    originalPrice: 950,
    rating: 4.9,
    reviewCount: 165,
    dosha: "vata",
    doshaLabel: "Vata Nourishing",
    benefits: ["Digestion & Gut", "Energy & Vitality"],
    organic: true,
    inStock: true,
    stockCount: 22,
    icon: "🧈",
    image: "https://images.unsplash.com/photo-1589927986089-35812388d1f4?auto=format&fit=crop&w=600&q=80",
    description: "Traditional Bilona method grass-fed cultured A2 ghee for strengthening Agni (digestive fire) and Ojas.",
    ingredients: ["100% Grass-Fed A2 Gir Cow Cultured Butter"],
    dosage: "1 tablespoon in morning beverages or warm food.",
    certifications: ["Bilona Churned", "A2 Certified", "Lactose-Free"]
  },
  {
    id: 12,
    name: "Kumkumadi Tailam Miraculous Face Oil (30ml)",
    category: "oils-ghee",
    categoryLabel: "Oils & Ghee",
    price: 999,
    originalPrice: 1299,
    rating: 5.0,
    reviewCount: 210,
    dosha: "pitta",
    doshaLabel: "Pitta Pacifying",
    benefits: ["Skin Glow & Hair"],
    organic: true,
    inStock: true,
    stockCount: 18,
    icon: "🧴",
    image: "https://images.unsplash.com/photo-1601049541289-9b1b7bbbfe19?auto=format&fit=crop&w=600&q=80",
    description: "Legendary Ayurvedic beauty elixir crafted with Kashmiri Saffron, Red Sandalwood, and 24 precious botanical herbs.",
    ingredients: ["Kashmiri Saffron", "Red Sandalwood", "Lotus Petals", "Sesame Oil"],
    dosage: "Gently massage 3-4 drops onto clean face before sleep.",
    certifications: ["100% Pure Botanical", "Dermatologist Tested", "Cruelty-Free"]
  },
  {
    id: 13,
    name: "Mahanarayan Therapeutic Joint & Muscle Oil",
    category: "oils-ghee",
    categoryLabel: "Oils & Ghee",
    price: 499,
    originalPrice: 620,
    rating: 4.9,
    reviewCount: 112,
    dosha: "vata",
    doshaLabel: "Vata Soothing",
    benefits: ["Joint & Muscle Care"],
    organic: true,
    inStock: true,
    stockCount: 25,
    icon: "🏺",
    image: "https://images.unsplash.com/photo-1544367567-0f2fcb009e0b?auto=format&fit=crop&w=600&q=80",
    description: "Ancient herbal massage formula with Dashamoola and Camphor for easing sore joints and stiff muscles.",
    ingredients: ["Dashamoola Extracts", "Eucalyptus", "Pure Sesame Base", "Camphor"],
    dosage: "Warm slightly and massage into joints in circular motions.",
    certifications: ["Classical Recipe", "100% Natural"]
  },
  {
    id: 14,
    name: "Bhringraj & Rosemary Scalp Revitalizer Oil",
    category: "oils-ghee",
    categoryLabel: "Oils & Ghee",
    price: 449,
    originalPrice: 580,
    rating: 4.8,
    reviewCount: 135,
    dosha: "pitta",
    doshaLabel: "Pitta Cooling Scalp",
    benefits: ["Skin Glow & Hair"],
    organic: true,
    inStock: true,
    stockCount: 40,
    icon: "💆",
    image: "https://images.unsplash.com/photo-1522337360788-8b13dee7a37e?auto=format&fit=crop&w=600&q=80",
    description: "King of herbs for hair growth simmered with rosemary, fenugreek, and cold-pressed coconut oil.",
    ingredients: ["Bhringraj Leaf Extract", "Rosemary Oil", "Virgin Coconut Oil", "Amla"],
    dosage: "Massage into scalp 2 hours before washing or overnight.",
    certifications: ["Cold-Pressed", "Zero Mineral Oils"]
  },
  {
    id: 15,
    name: "Ksheerabala Tailam Calming Vata Oil",
    category: "oils-ghee",
    categoryLabel: "Oils & Ghee",
    price: 379,
    originalPrice: 470,
    rating: 4.8,
    reviewCount: 64,
    dosha: "vata",
    doshaLabel: "Vata Grounding",
    benefits: ["Stress & Sleep", "Joint & Muscle Care"],
    organic: true,
    inStock: true,
    stockCount: 32,
    icon: "✨",
    image: "https://images.unsplash.com/photo-1617897903246-719242758050?auto=format&fit=crop&w=600&q=80",
    description: "Bala root processed in pure cow's milk and sesame oil for neuromuscular soothing and insomnia relief.",
    ingredients: ["Sida Cordifolia (Bala)", "Cow Milk", "Gingelly Oil"],
    dosage: "Apply warm oil over head, neck, and feet before bed.",
    certifications: ["Classical Ayurvedic Formulation"]
  },
  {
    id: 16,
    name: "Anu Tailam Ayurvedic Nasal Nasya Drops",
    category: "oils-ghee",
    categoryLabel: "Oils & Ghee",
    price: 199,
    originalPrice: 260,
    rating: 4.9,
    reviewCount: 180,
    dosha: "kapha",
    doshaLabel: "Kapha Clearing",
    benefits: ["Immunity Boost", "Stress & Sleep"],
    organic: true,
    inStock: true,
    stockCount: 65,
    icon: "👃",
    image: "https://images.unsplash.com/photo-1608248597359-2ff96954b830?auto=format&fit=crop&w=600&q=80",
    description: "Potent 28-herb nasal elixir clearing sinuses, relieving tension headaches, and improving sleep quality.",
    ingredients: ["Cedarwood", "Licorice", "Nutgrass", "Sesame Oil"],
    dosage: "2 drops in each nostril every morning.",
    certifications: ["AYUSH Approved", "Classical Nasya"]
  },
  {
    id: 17,
    name: "Dhanwantharam Abhyanga Body Massage Oil",
    category: "oils-ghee",
    categoryLabel: "Oils & Ghee",
    price: 529,
    originalPrice: 650,
    rating: 4.9,
    reviewCount: 95,
    dosha: "vata",
    doshaLabel: "Vata Pacifying",
    benefits: ["Joint & Muscle Care", "Energy & Vitality"],
    organic: true,
    inStock: true,
    stockCount: 28,
    icon: "🏺",
    image: "https://images.unsplash.com/photo-1540555700478-4be289fbecef?auto=format&fit=crop&w=600&q=80",
    description: "Complete full-body Abhyanga oil with Bala and Ashwagandha to tone muscles and hydrate tissues.",
    ingredients: ["Bala", "Ashwagandha", "Dashamoola", "Sesame Base"],
    dosage: "Massage full body in circular strokes 30 mins before bathing.",
    certifications: ["Kerala Ayurvedic Heritage"]
  },
  {
    id: 18,
    name: "Organic Cold-Pressed Castor & Almond Oil",
    category: "oils-ghee",
    categoryLabel: "Oils & Ghee",
    price: 349,
    originalPrice: 420,
    rating: 4.7,
    reviewCount: 88,
    dosha: "tridoshic",
    doshaLabel: "Tridoshic Nourishment",
    benefits: ["Skin Glow & Hair", "Digestion & Gut"],
    organic: true,
    inStock: true,
    stockCount: 42,
    icon: "🌰",
    image: "https://images.unsplash.com/photo-1598440947619-2c35fc9aa908?auto=format&fit=crop&w=600&q=80",
    description: "Hexane-free cold-pressed ricinoleic elixir for eyebrow thickness, dry skin patches, and belly button oiling.",
    ingredients: ["100% Pure Virgin Castor Oil", "Sweet Almond Oil"],
    dosage: "Apply gently to lashes, brows, joints, or navel.",
    certifications: ["Hexane-Free", "USDA Organic"]
  },

  // =========================================================================
  // 3. TEAS, TONICS & INFUSIONS (8 Unique Products)
  // =========================================================================
  {
    id: 19,
    name: "Tulsi Holy Basil & Ginger Elixir Tea",
    category: "teas-infusions",
    categoryLabel: "Teas & Infusions",
    price: 249,
    originalPrice: 320,
    rating: 4.7,
    reviewCount: 84,
    dosha: "kapha",
    doshaLabel: "Kapha Stimulating",
    benefits: ["Immunity Boost", "Stress & Sleep"],
    organic: true,
    inStock: true,
    stockCount: 65,
    icon: "🍵",
    image: "https://images.unsplash.com/photo-1576092768241-dec231879fc3?auto=format&fit=crop&w=600&q=80",
    description: "Healing blend of Rama, Krishna & Vana Tulsi herbs with organic spicy sun-dried ginger for respiratory health.",
    ingredients: ["Rama Tulsi", "Krishna Tulsi", "Vana Tulsi", "Sun-Dried Ginger"],
    dosage: "Steep 1 tea bag or tsp for 4-5 minutes in boiling water.",
    certifications: ["Fairtrade Certified", "100% Organic"]
  },
  {
    id: 20,
    name: "Golden Milk Haldi Latte Superfood Blend",
    category: "teas-infusions",
    categoryLabel: "Teas & Infusions",
    price: 379,
    originalPrice: 480,
    rating: 4.9,
    reviewCount: 140,
    dosha: "vata",
    doshaLabel: "Vata Grounding Warmth",
    benefits: ["Immunity Boost", "Joint & Muscle Care"],
    organic: true,
    inStock: true,
    stockCount: 52,
    icon: "🥛",
    image: "https://images.unsplash.com/photo-1544787219-7f47ccb76574?auto=format&fit=crop&w=600&q=80",
    description: "Lakadong 7% curcumin turmeric paired with Ceylon cinnamon, green cardamom, black pepper, and ginger.",
    ingredients: ["Lakadong Turmeric", "Ceylon Cinnamon", "Cardamom", "Black Pepper"],
    dosage: "Whisk 1 tsp into warm oat, almond, or dairy milk.",
    certifications: ["High Curcumin", "Sugar Free"]
  },
  {
    id: 21,
    name: "Kashmiri Kahwa Saffron & Cardamom Green Tea",
    category: "teas-infusions",
    categoryLabel: "Teas & Infusions",
    price: 399,
    originalPrice: 520,
    rating: 4.9,
    reviewCount: 96,
    dosha: "kapha",
    doshaLabel: "Kapha Invigorating",
    benefits: ["Digestion & Gut", "Energy & Vitality"],
    organic: true,
    inStock: true,
    stockCount: 38,
    icon: "☕",
    image: "https://images.unsplash.com/photo-1564890369478-c89ca6d9cde9?auto=format&fit=crop&w=600&q=80",
    description: "Regal blend of whole green tea leaves, crushed Kashmiri almonds, saffron threads, and warm spices.",
    ingredients: ["Green Tea", "Kashmiri Saffron", "Green Cardamom", "Almonds", "Clove"],
    dosage: "Infuse 2g in 90°C water for 3-4 mins.",
    certifications: ["Artisanal Harvest", "Natural Aroma"]
  },
  {
    id: 22,
    name: "Hibiscus & Rose Pitta Cooling Tisane",
    category: "teas-infusions",
    categoryLabel: "Teas & Infusions",
    price: 299,
    originalPrice: 380,
    rating: 4.8,
    reviewCount: 68,
    dosha: "pitta",
    doshaLabel: "Pitta Cooling Elixir",
    benefits: ["Skin Glow & Hair", "Stress & Sleep"],
    organic: true,
    inStock: true,
    stockCount: 45,
    icon: "🌺",
    image: "https://images.unsplash.com/photo-1597481499750-3e6b22637e12?auto=format&fit=crop&w=600&q=80",
    description: "Crisp ruby floral infusion that gently clears excess internal heat, calms irritability, and hydrates skin.",
    ingredients: ["Organic Dried Hibiscus Petals", "Damask Rose", "Fennel Seeds", "Mint"],
    dosage: "Enjoy warm or chilled with a hint of raw honey.",
    certifications: ["Caffeine-Free", "100% Botanical"]
  },
  {
    id: 23,
    name: "Chamomile & Brahmi Deep Sleep Infusion",
    category: "teas-infusions",
    categoryLabel: "Teas & Infusions",
    price: 329,
    originalPrice: 420,
    rating: 4.9,
    reviewCount: 115,
    dosha: "vata",
    doshaLabel: "Vata Tranquility",
    benefits: ["Stress & Sleep"],
    organic: true,
    inStock: true,
    stockCount: 40,
    icon: "💤",
    image: "https://images.unsplash.com/photo-1571934811356-5cc597d25e0a?auto=format&fit=crop&w=600&q=80",
    description: "Synergistic botanical sedative blend calming nervous exhaustion and racing thoughts before sleep.",
    ingredients: ["Egyptian Chamomile", "Brahmi", "Shankhpushpi", "Lavender Flowers"],
    dosage: "Sip 1 warm mug 45 minutes before bedtime.",
    certifications: ["Non-Habit Forming", "Organic"]
  },
  {
    id: 24,
    name: "CCF Classic Agni Digestive Detox Tea",
    category: "teas-infusions",
    categoryLabel: "Teas & Infusions",
    price: 229,
    originalPrice: 299,
    rating: 4.8,
    reviewCount: 92,
    dosha: "tridoshic",
    doshaLabel: "Tridoshic Metabolism",
    benefits: ["Digestion & Gut"],
    organic: true,
    inStock: true,
    stockCount: 58,
    icon: "🫖",
    image: "https://images.unsplash.com/photo-1594631252845-29fc4cc8cde9?auto=format&fit=crop&w=600&q=80",
    description: "Ayurveda's most renowned equal-ratio blend of Cumin, Coriander, and Fennel seeds for bloating relief.",
    ingredients: ["Whole Cumin Seeds", "Coriander Seeds", "Sweet Fennel Seeds"],
    dosage: "Boil 1 tbsp in 500ml water for 5 mins; sip throughout the day.",
    certifications: ["100% Raw Spices", "Zero Additives"]
  },
  {
    id: 25,
    name: "Moringa & Lemongrass Cellular Energizer",
    category: "teas-infusions",
    categoryLabel: "Teas & Infusions",
    price: 269,
    originalPrice: 340,
    rating: 4.7,
    reviewCount: 54,
    dosha: "kapha",
    doshaLabel: "Kapha Metabolism Booster",
    benefits: ["Energy & Vitality", "Immunity Boost"],
    organic: true,
    inStock: true,
    stockCount: 44,
    icon: "🌿",
    image: "https://images.unsplash.com/photo-1563911892437-1feda0179e1b?auto=format&fit=crop&w=600&q=80",
    description: "Nutrient-dense drumstick leaf with zesty lemongrass providing jitter-free clean natural stamina.",
    ingredients: ["Organic Moringa Oleifera Leaf", "Fresh Lemongrass"],
    dosage: "Brew 1 cup during morning or afternoon slump.",
    certifications: ["Superfood Certified", "Vegan"]
  },
  {
    id: 26,
    name: "Licorice & Ginger Throat Comfort Brew",
    category: "teas-infusions",
    categoryLabel: "Teas & Infusions",
    price: 249,
    originalPrice: 320,
    rating: 4.8,
    reviewCount: 77,
    dosha: "kapha",
    doshaLabel: "Kapha Soothing",
    benefits: ["Immunity Boost", "Digestion & Gut"],
    organic: true,
    inStock: true,
    stockCount: 50,
    icon: "🫚",
    image: "https://images.unsplash.com/photo-1576092768241-dec231879fc3?auto=format&fit=crop&w=600&q=80",
    description: "Yashtimadhu root with sun-dried ginger and black pepper to coat vocal cords and soothe coughs.",
    ingredients: ["Yashtimadhu Licorice Root", "Dry Ginger", "Kantakari"],
    dosage: "Steep 5 mins in boiling water and enjoy warm.",
    certifications: ["Naturally Sweet", "No Added Sugar"]
  },

  // =========================================================================
  // 4. CLASSICAL VATIS, GUGGULU & CHURNAS (8 Unique Products)
  // =========================================================================
  {
    id: 27,
    name: "Yograj Guggulu Joint Stiffness Tablets",
    category: "classical-churnas",
    categoryLabel: "Classical Vatis & Churnas",
    price: 369,
    originalPrice: 470,
    rating: 4.9,
    reviewCount: 128,
    dosha: "vata",
    doshaLabel: "Vata Joint Health",
    benefits: ["Joint & Muscle Care"],
    organic: true,
    inStock: true,
    stockCount: 36,
    icon: "🏺",
    image: "https://images.unsplash.com/photo-1584308666744-24d5c474f2ae?auto=format&fit=crop&w=600&q=80",
    description: "Classical formulation of 27 herbs purified in Guggulu resin for joint mobility and chronic Vata aches.",
    ingredients: ["Shuddha Guggulu", "Chitrak", "Pippali", "Triphala"],
    dosage: "2 tablets twice daily with warm water or Maharasnadi Kwath.",
    certifications: ["Bhasma Standardized", "GMP Approved"]
  },
  {
    id: 28,
    name: "Kanchnar Guggulu Lymphatic Support",
    category: "classical-churnas",
    categoryLabel: "Classical Vatis & Churnas",
    price: 399,
    originalPrice: 510,
    rating: 4.8,
    reviewCount: 94,
    dosha: "kapha",
    doshaLabel: "Kapha Detox",
    benefits: ["Immunity Boost", "Skin Glow & Hair"],
    organic: true,
    inStock: true,
    stockCount: 28,
    icon: "🍃",
    image: "https://images.unsplash.com/photo-1584017911766-d451b3d0e843?auto=format&fit=crop&w=600&q=80",
    description: "Renowned Ayurvedic recipe for glandular health, thyroid balance, and lymphatic drainage.",
    ingredients: ["Kanchnar Bark", "Trikatu", "Varuna", "Triphala", "Guggulu"],
    dosage: "2 tablets twice daily after meals.",
    certifications: ["AYUSH Pharmacopoeia", "Pure Guggul"]
  },
  {
    id: 29,
    name: "Trikatu Churna Metabolism & Agni Powder",
    category: "classical-churnas",
    categoryLabel: "Classical Vatis & Churnas",
    price: 199,
    originalPrice: 260,
    rating: 4.7,
    reviewCount: 83,
    dosha: "kapha",
    doshaLabel: "Kapha & Vata Kindle",
    benefits: ["Digestion & Gut", "Energy & Vitality"],
    organic: true,
    inStock: true,
    stockCount: 60,
    icon: "🌶️",
    image: "https://images.unsplash.com/photo-1596040033229-a9821ebd058d?auto=format&fit=crop&w=600&q=80",
    description: "The 'Three Pungents' (Black Pepper, Long Pepper, Ginger) to ignite sluggish digestive fire and clear mucus.",
    ingredients: ["Black Pepper (Maricha)", "Long Pepper (Pippali)", "Dry Ginger (Sunthi)"],
    dosage: "1/4 teaspoon mixed with raw honey before main meals.",
    certifications: ["100% Spices", "Chemical Free"]
  },
  {
    id: 30,
    name: "Sitopaladi Churna Respiratory Defense",
    category: "classical-churnas",
    categoryLabel: "Classical Vatis & Churnas",
    price: 249,
    originalPrice: 320,
    rating: 4.9,
    reviewCount: 160,
    dosha: "pitta",
    doshaLabel: "Pitta & Kapha Respiratory",
    benefits: ["Immunity Boost"],
    organic: true,
    inStock: true,
    stockCount: 45,
    icon: "🌾",
    image: "https://images.unsplash.com/photo-1546868871-7041f2a55e12?auto=format&fit=crop&w=600&q=80",
    description: "Traditional Ayurvedic remedy for seasonal chest congestion, dry cough, and soothing lung irritation.",
    ingredients: ["Mishri Rock Sugar", "Vanshlochan (Bamboo Manna)", "Pippali", "Cardamom", "Cinnamon"],
    dosage: "1/2 tsp twice daily with ghee or honey.",
    certifications: ["Classical Recipe", "Safe for Children"]
  },
  {
    id: 31,
    name: "Shankhpushpi Medhya Syrup (200ml)",
    category: "classical-churnas",
    categoryLabel: "Classical Vatis & Churnas",
    price: 229,
    originalPrice: 290,
    rating: 4.8,
    reviewCount: 90,
    dosha: "pitta",
    doshaLabel: "Pitta Mental Calm",
    benefits: ["Stress & Sleep"],
    organic: true,
    inStock: true,
    stockCount: 35,
    icon: "🧠",
    image: "https://images.unsplash.com/photo-1628088062854-d1870b4553da?auto=format&fit=crop&w=600&q=80",
    description: "Herbal memory booster and nerve tonic helping reduce exam anxiety, stress, and nervous fatigue.",
    ingredients: ["Shankhpushpi (Convolvulus Pluricaulis)", "Brahmi", "Nimbu Satva"],
    dosage: "1-2 teaspoons morning and evening with water.",
    certifications: ["Ayurvedic Proprietary", "Sugar-Monitored"]
  },
  {
    id: 32,
    name: "Avipattikar Churna Hyperacidity Care",
    category: "classical-churnas",
    categoryLabel: "Classical Vatis & Churnas",
    price: 219,
    originalPrice: 280,
    rating: 4.8,
    reviewCount: 104,
    dosha: "pitta",
    doshaLabel: "Pitta Acid Balancing",
    benefits: ["Digestion & Gut"],
    organic: true,
    inStock: true,
    stockCount: 48,
    icon: "🥣",
    image: "https://images.unsplash.com/photo-1509316975850-ff9c5deb0cd9?auto=format&fit=crop&w=600&q=80",
    description: "Classical cooling digestive churna neutralizing heartburn, acid reflux, sour belching, and constipation.",
    ingredients: ["Triphala", "Trikatu", "Musta", "Cardamom", "Nishoth", "Clove"],
    dosage: "1 teaspoon with cool water before lunch and dinner.",
    certifications: ["Zero Chemicals", "Rapid Relief"]
  },
  {
    id: 33,
    name: "Chandraprabha Vati Kidney & Urinary Balance",
    category: "classical-churnas",
    categoryLabel: "Classical Vatis & Churnas",
    price: 349,
    originalPrice: 440,
    rating: 4.7,
    reviewCount: 67,
    dosha: "vata",
    doshaLabel: "Vata & Pitta Urinary Support",
    benefits: ["Energy & Vitality"],
    organic: true,
    inStock: true,
    stockCount: 40,
    icon: "🌕",
    image: "https://images.unsplash.com/photo-1587854692152-cbe660dbde88?auto=format&fit=crop&w=600&q=80",
    description: "Potent 37-herb formula promoting bladder strength, uric acid balance, and prostate vitality.",
    ingredients: ["Shilajit", "Guggulu", "Chitrak", "Daruharidra", "Swarna Makshik Bhasma"],
    dosage: "1-2 tablets twice daily with water.",
    certifications: ["Classical Bhasma", "AYUSH Standard"]
  },
  {
    id: 34,
    name: "Mahasudarshan Vati Seasonal Defense",
    category: "classical-churnas",
    categoryLabel: "Classical Vatis & Churnas",
    price: 299,
    originalPrice: 380,
    rating: 4.8,
    reviewCount: 79,
    dosha: "pitta",
    doshaLabel: "Pitta & Kapha Cleansing",
    benefits: ["Immunity Boost"],
    organic: true,
    inStock: true,
    stockCount: 50,
    icon: "🛡️",
    image: "https://images.unsplash.com/photo-1550572017-edd951aa8f72?auto=format&fit=crop&w=600&q=80",
    description: "Famous multi-herb bitter tablet known for purifying blood, cooling fevers, and balancing all three doshas.",
    ingredients: ["Kiratatikta (Chirata)", "Guduchi", "Haridra", "Kutki"],
    dosage: "1 tablet twice daily with warm water.",
    certifications: ["Bitter Tonic", "Classical Formula"]
  },

  // =========================================================================
  // 5. NATURAL AYURVEDIC SKINCARE (10 Unique Products)
  // =========================================================================
  {
    id: 35,
    name: "Neem & Turmeric Clarifying Body Bar",
    category: "natural-skincare",
    categoryLabel: "Natural Skincare",
    price: 199,
    originalPrice: 249,
    rating: 4.6,
    reviewCount: 94,
    dosha: "pitta",
    doshaLabel: "Pitta Detox",
    benefits: ["Skin Glow & Hair"],
    organic: true,
    inStock: true,
    stockCount: 80,
    icon: "🧼",
    image: "https://images.unsplash.com/photo-1607006311820-d657172f1056?auto=format&fit=crop&w=600&q=80",
    description: "Cold-pressed handcrafted soap infused with organic wild neem leaf and antiseptic golden turmeric.",
    ingredients: ["Organic Neem Leaf", "Kasturi Manjal Turmeric", "Coconut Oil", "Shea Butter"],
    dosage: "Lather generously during bath or shower.",
    certifications: ["Sulfate-Free", "Zero Palm Oil", "Handmade"]
  },
  {
    id: 36,
    name: "Pure Damask Rose & Vetiver Hydrating Mist",
    category: "natural-skincare",
    categoryLabel: "Natural Skincare",
    price: 349,
    originalPrice: 450,
    rating: 4.9,
    reviewCount: 156,
    dosha: "pitta",
    doshaLabel: "Pitta Cooling Mist",
    benefits: ["Skin Glow & Hair"],
    organic: true,
    inStock: true,
    stockCount: 42,
    icon: "🌹",
    image: "https://images.unsplash.com/photo-1616949755610-8c9bbc08f138?auto=format&fit=crop&w=600&q=80",
    description: "Steam-distilled Kannauj rose water combined with grounding Vetiver roots to tone pores and refresh skin.",
    ingredients: ["100% Steam-Distilled Rose Petal Hydrosol", "Vetiver Root Distillate"],
    dosage: "Spritz generously over face and neck morning and night.",
    certifications: ["Pure Hydrosol", "Zero Alcohol"]
  },
  {
    id: 37,
    name: "Ubtan Radiance Body & Face Polish",
    category: "natural-skincare",
    categoryLabel: "Natural Skincare",
    price: 429,
    originalPrice: 560,
    rating: 4.9,
    reviewCount: 118,
    dosha: "tridoshic",
    doshaLabel: "Tridoshic Glow",
    benefits: ["Skin Glow & Hair"],
    organic: true,
    inStock: true,
    stockCount: 30,
    icon: "✨",
    image: "https://images.unsplash.com/photo-1556228720-195a672e8a03?auto=format&fit=crop&w=600&q=80",
    description: "Centuries-old bridal glow recipe blending Chickpea flour, Kashmiri Saffron, Almonds, and Sandalwood.",
    ingredients: ["Besan Gram Flour", "Kasturi Manjal", "Sweet Almond Meal", "Red Sandalwood"],
    dosage: "Mix with raw milk or rose water into paste; gently scrub and rinse.",
    certifications: ["100% Edible Grade", "Microplastic Free"]
  },
  {
    id: 38,
    name: "Sandalwood & Saffron Skin Brightening Cream",
    category: "natural-skincare",
    categoryLabel: "Natural Skincare",
    price: 699,
    originalPrice: 899,
    rating: 5.0,
    reviewCount: 145,
    dosha: "pitta",
    doshaLabel: "Pitta Balancing",
    benefits: ["Skin Glow & Hair"],
    organic: true,
    inStock: true,
    stockCount: 24,
    icon: "🧴",
    image: "https://images.unsplash.com/photo-1570172619644-dfd03ed5d881?auto=format&fit=crop&w=600&q=80",
    description: "Rich day cream formulated with Shata Dhauta Ghrita (100 times washed ghee), pure sandalwood, and saffron.",
    ingredients: ["100x Washed A2 Ghee", "Mysore Chandan", "Kashmiri Kesar", "Lotus Stamen"],
    dosage: "Smooth pea-sized amount onto face in upward strokes.",
    certifications: ["Paraben Free", "Dermatologist Tested"]
  },
  {
    id: 39,
    name: "Pure Aloe Vera & Kesar Soothing Gel (200g)",
    category: "natural-skincare",
    categoryLabel: "Natural Skincare",
    price: 279,
    originalPrice: 350,
    rating: 4.8,
    reviewCount: 92,
    dosha: "pitta",
    doshaLabel: "Pitta Hydration",
    benefits: ["Skin Glow & Hair"],
    organic: true,
    inStock: true,
    stockCount: 65,
    icon: "🌱",
    image: "https://images.unsplash.com/photo-1596755094514-f87e34085b2c?auto=format&fit=crop&w=600&q=80",
    description: "Cold-extracted organic inner leaf aloe vera gel infused with golden saffron threads for sunburn and daily hydration.",
    ingredients: ["99% Pure Organic Aloe Vera Juice", "Kesar Extract", "Vitamin E"],
    dosage: "Apply liberally on face, body, or scalp after sun exposure.",
    certifications: ["Zero Artificial Fragrance", "Non-Sticky"]
  },
  {
    id: 40,
    name: "Kumkumadi Rejuvenating Night Cream (50g)",
    category: "natural-skincare",
    categoryLabel: "Natural Skincare",
    price: 799,
    originalPrice: 999,
    rating: 4.9,
    reviewCount: 130,
    dosha: "vata",
    doshaLabel: "Vata & Pitta Renewal",
    benefits: ["Skin Glow & Hair"],
    organic: true,
    inStock: true,
    stockCount: 20,
    icon: "🌙",
    image: "https://images.unsplash.com/photo-1567928815104-b63309a01f5c?auto=format&fit=crop&w=600&q=80",
    description: "Intense overnight barrier repair balm harnessing Kumkumadi Tailam and Kokum butter for fine lines and dark spots.",
    ingredients: ["Kumkumadi Tailam", "Kokum Seed Butter", "Manjistha", "Licorice"],
    dosage: "Massage onto clean face before bed.",
    certifications: ["Cruelty-Free", "Rich Herbal Blend"]
  },
  {
    id: 41,
    name: "Bakuchiol Natural Plant Retinol Serum (30ml)",
    category: "natural-skincare",
    categoryLabel: "Natural Skincare",
    price: 849,
    originalPrice: 1099,
    rating: 4.9,
    reviewCount: 88,
    dosha: "tridoshic",
    doshaLabel: "Tridoshic Anti-Aging",
    benefits: ["Skin Glow & Hair"],
    organic: true,
    inStock: true,
    stockCount: 25,
    icon: "🧪",
    image: "https://images.unsplash.com/photo-1620916566398-39f1143ab7be?auto=format&fit=crop&w=600&q=80",
    description: "Gentle Babchi seed extract giving all cellular renewal benefits of retinol without redness, peeling, or irritation.",
    ingredients: ["1% Pure Bakuchiol (Babchi)", "Cold-Pressed Jojoba Oil", "Rosehip Seed Oil"],
    dosage: "Apply 3-4 drops nightly before moisturizer.",
    certifications: ["100% Plant-Derived", "Safe for Sensitive Skin"]
  },
  {
    id: 42,
    name: "Gotu Kola & Coffee Firming Eye Elixir",
    category: "natural-skincare",
    categoryLabel: "Natural Skincare",
    price: 499,
    originalPrice: 650,
    rating: 4.7,
    reviewCount: 75,
    dosha: "pitta",
    doshaLabel: "Pitta Eye Soother",
    benefits: ["Skin Glow & Hair", "Stress & Sleep"],
    organic: true,
    inStock: true,
    stockCount: 30,
    icon: "👁️",
    image: "https://images.unsplash.com/photo-1512290900672-1f486240d425?auto=format&fit=crop&w=600&q=80",
    description: "Centella Asiatica and green coffee bean oil roll-on to diminish dark circles, puffy eyelids, and screen fatigue.",
    ingredients: ["Gotu Kola (Mandukaparni)", "Green Coffee Extract", "Almond Oil", "Cucumber Hydrosol"],
    dosage: "Glide cooling metal rollerball around orbital bone morning & night.",
    certifications: ["Ophthalmologist Tested"]
  },
  {
    id: 43,
    name: "Multani Mitti & Sandalwood Clay Mask",
    category: "natural-skincare",
    categoryLabel: "Natural Skincare",
    price: 299,
    originalPrice: 380,
    rating: 4.8,
    reviewCount: 110,
    dosha: "kapha",
    doshaLabel: "Kapha Oil Control",
    benefits: ["Skin Glow & Hair"],
    organic: true,
    inStock: true,
    stockCount: 50,
    icon: "🏺",
    image: "https://images.unsplash.com/photo-1598440947619-2c35fc9aa908?auto=format&fit=crop&w=600&q=80",
    description: "Sun-dried Fuller's Earth with Mysore white sandalwood to draw out deep blackheads and excess sebum.",
    ingredients: ["Natural Multani Mitti Clay", "White Sandalwood Powder", "Lodhra", "Neem Bark"],
    dosage: "Mix 1 tbsp with rose water, leave on face for 10 mins; wash off.",
    certifications: ["100% Natural Earth", "Chemical Free"]
  },
  {
    id: 44,
    name: "Handcrafted Jasmine & Moringa Body Butter",
    category: "natural-skincare",
    categoryLabel: "Natural Skincare",
    price: 549,
    originalPrice: 699,
    rating: 4.9,
    reviewCount: 82,
    dosha: "vata",
    doshaLabel: "Vata Nourishing Butter",
    benefits: ["Skin Glow & Hair"],
    organic: true,
    inStock: true,
    stockCount: 22,
    icon: "🧈",
    image: "https://images.unsplash.com/photo-1547887537-6158d64c35b3?auto=format&fit=crop&w=600&q=80",
    description: "Decadent whipped body cream made with Madurai Mogra jasmine flowers and cold-pressed Moringa seed oil.",
    ingredients: ["Mango Seed Butter", "Moringa Seed Oil", "Mogra Jasmine Essential Oil", "Shea Butter"],
    dosage: "Massage into damp skin after bathing.",
    certifications: ["Vegan", "Zero Artificial Fragrance"]
  },

  // =========================================================================
  // 6. HAIR & SCALP CARE (6 Unique Products)
  // =========================================================================
  {
    id: 45,
    name: "Shikakai & Reetha Gentle Herbal Shampoo Bar",
    category: "hair-scalp",
    categoryLabel: "Hair & Scalp Care",
    price: 249,
    originalPrice: 320,
    rating: 4.8,
    reviewCount: 95,
    dosha: "pitta",
    doshaLabel: "Pitta Scalp Balance",
    benefits: ["Skin Glow & Hair"],
    organic: true,
    inStock: true,
    stockCount: 60,
    icon: "🧼",
    image: "https://images.unsplash.com/photo-1607006483702-39c4f1c1f7a6?auto=format&fit=crop&w=600&q=80",
    description: "Zero-waste solid shampoo bar naturally lathering with soapnuts (Reetha), Shikakai fruit, and Amla.",
    ingredients: ["Reetha (Soapnut)", "Shikakai", "Amla", "Hibiscus", "Coconut Oil Base"],
    dosage: "Rub bar onto wet scalp to create lather; rinse thoroughly.",
    certifications: ["Zero Plastic", "Sulfate & Silicone Free"]
  },
  {
    id: 46,
    name: "Red Onion & Bhringraj Anti-Hairfall Elixir",
    category: "hair-scalp",
    categoryLabel: "Hair & Scalp Care",
    price: 499,
    originalPrice: 650,
    rating: 4.9,
    reviewCount: 175,
    dosha: "vata",
    doshaLabel: "Vata Follicle Strengthener",
    benefits: ["Skin Glow & Hair"],
    organic: true,
    inStock: true,
    stockCount: 35,
    icon: "🧅",
    image: "https://images.unsplash.com/photo-1608248597359-2ff96954b830?auto=format&fit=crop&w=600&q=80",
    description: "Sulphur-rich red onion bulb extract combined with 14 Ayurvedic herbs to strengthen roots and curb hair thinning.",
    ingredients: ["Red Onion Seed Oil", "Bhringraj Extract", "Black Seed (Kalonji) Oil", "Fenugreek"],
    dosage: "Apply directly to scalp with dropper 3 times a week.",
    certifications: ["Clinically Tested", "Mineral Oil Free"]
  },
  {
    id: 47,
    name: "Hibiscus & Fenugreek Deep Nourish Hair Mask",
    category: "hair-scalp",
    categoryLabel: "Hair & Scalp Care",
    price: 399,
    originalPrice: 520,
    rating: 4.8,
    reviewCount: 88,
    dosha: "vata",
    doshaLabel: "Vata Dry Hair Repair",
    benefits: ["Skin Glow & Hair"],
    organic: true,
    inStock: true,
    stockCount: 28,
    icon: "🌺",
    image: "https://images.unsplash.com/photo-1527799820374-dcf8d9d4a388?auto=format&fit=crop&w=600&q=80",
    description: "Creamy intensive hair conditioning spa butter repairing heat damage, split ends, and frizzy tresses.",
    ingredients: ["Fresh Hibiscus Leaf Pulp", "Sprouted Methi (Fenugreek)", "Coconut Milk", "Argan Oil"],
    dosage: "Apply from roots to tips; leave for 20 minutes before shampooing.",
    certifications: ["100% Natural Botanicals"]
  },
  {
    id: 48,
    name: "Brahmi & Amla Scalp Stimulating Tonic",
    category: "hair-scalp",
    categoryLabel: "Hair & Scalp Care",
    price: 349,
    originalPrice: 450,
    rating: 4.7,
    reviewCount: 62,
    dosha: "pitta",
    doshaLabel: "Pitta Cooling Tonic",
    benefits: ["Skin Glow & Hair"],
    organic: true,
    inStock: true,
    stockCount: 40,
    icon: "💧",
    image: "https://images.unsplash.com/photo-1535585209827-a15fcdbc4c2d?auto=format&fit=crop&w=600&q=80",
    description: "Lightweight, non-oily water-based herbal spray that boosts microcirculation in follicles and prevents premature greying.",
    ingredients: ["Hydrolyzed Brahmi Extract", "Fresh Amla Juice", "Jatamansi", "Rosemary Water"],
    dosage: "Spray onto scalp daily morning and evening; no rinse needed.",
    certifications: ["Non-Greasy Formula", "AYUSH Approved"]
  },
  {
    id: 49,
    name: "Virgin Coconut & Curry Leaf Scalp Infusion",
    category: "hair-scalp",
    categoryLabel: "Hair & Scalp Care",
    price: 329,
    originalPrice: 420,
    rating: 4.9,
    reviewCount: 110,
    dosha: "pitta",
    doshaLabel: "Pitta & Vata Hair Care",
    benefits: ["Skin Glow & Hair"],
    organic: true,
    inStock: true,
    stockCount: 48,
    icon: "🥥",
    image: "https://images.unsplash.com/photo-1584308666744-24d5c474f2ae?auto=format&fit=crop&w=600&q=80",
    description: "Slow-cooked South Indian recipe using fresh curry leaves in virgin wood-pressed coconut oil to preserve natural melanin.",
    ingredients: ["Cold-Pressed Virgin Coconut Oil", "Organic Fresh Curry Leaves", "Methi Seeds"],
    dosage: "Massage into hair lengths and scalp 1 hour before bath.",
    certifications: ["Slow Wood-Pressed", "Traditional Recipe"]
  },
  {
    id: 50,
    name: "Organic Henna & Indigo Herbal Hair Color",
    category: "hair-scalp",
    categoryLabel: "Hair & Scalp Care",
    price: 299,
    originalPrice: 390,
    rating: 4.8,
    reviewCount: 95,
    dosha: "tridoshic",
    doshaLabel: "Chemical-Free Color",
    benefits: ["Skin Glow & Hair"],
    organic: true,
    inStock: true,
    stockCount: 50,
    icon: "🌿",
    image: "https://images.unsplash.com/photo-1540420773420-3366772f4999?auto=format&fit=crop&w=600&q=80",
    description: "Triple-sifted Sojat Henna and True Indigo leaves giving natural rich brown-to-black color without ammonia or PPD.",
    ingredients: ["100% Pure Lawsonia Inermis (Henna)", "Indigofera Tinctoria (Indigo)"],
    dosage: "Mix with warm water into paste; apply and wash off after 2 hours.",
    certifications: ["Zero Ammonia", "Zero PPD", "100% Plant Color"]
  },

  // =========================================================================
  // 7. AROMATHERAPY, DHOOP & INCENSE (6 Unique Products)
  // =========================================================================
  {
    id: 51,
    name: "Mysore Sandalwood & Frankincense Incense",
    category: "aromatherapy",
    categoryLabel: "Aromatherapy & Dhoop",
    price: 299,
    originalPrice: 380,
    rating: 4.8,
    reviewCount: 120,
    dosha: "vata",
    doshaLabel: "Vata Grounding",
    benefits: ["Stress & Sleep"],
    organic: true,
    inStock: true,
    stockCount: 90,
    icon: "🕯️",
    image: "https://images.unsplash.com/photo-1602928321679-560bb453f190?auto=format&fit=crop&w=600&q=80",
    description: "Hand-rolled sacred temple resin sticks without synthetic perfumes or toxic charcoal fillers.",
    ingredients: ["Mysore Sandalwood Powder", "Boswellia Serrata Resin", "Natural Gums"],
    dosage: "Light tip, blow out flame and place in holder.",
    certifications: ["Non-Toxic", "Charcoal Free", "Hand Rolled"]
  },
  {
    id: 52,
    name: "Pure Nilgiri Eucalyptus Essential Oil (15ml)",
    category: "aromatherapy",
    categoryLabel: "Aromatherapy & Dhoop",
    price: 249,
    originalPrice: 320,
    rating: 4.9,
    reviewCount: 88,
    dosha: "kapha",
    doshaLabel: "Kapha Decongestant",
    benefits: ["Immunity Boost"],
    organic: true,
    inStock: true,
    stockCount: 65,
    icon: "🌲",
    image: "https://images.unsplash.com/photo-1608571423902-eed4a5ad8108?auto=format&fit=crop&w=600&q=80",
    description: "Steam-distilled blue gum eucalyptus from Nilgiri hills to clear nasal passages and purify room air.",
    ingredients: ["100% Pure Eucalyptus Globulus Essential Oil"],
    dosage: "Add 3-5 drops to diffuser or steam inhaler.",
    certifications: ["Undiluted Pure", "Therapeutic Grade"]
  },
  {
    id: 53,
    name: "Lavender & Vetiver Calming Pillow Mist",
    category: "aromatherapy",
    categoryLabel: "Aromatherapy & Dhoop",
    price: 349,
    originalPrice: 450,
    rating: 4.9,
    reviewCount: 105,
    dosha: "vata",
    doshaLabel: "Vata Sleep Induction",
    benefits: ["Stress & Sleep"],
    organic: true,
    inStock: true,
    stockCount: 40,
    icon: "🛏️",
    image: "https://images.unsplash.com/photo-1595950653106-6c9ebd614d3a?auto=format&fit=crop&w=600&q=80",
    description: "Soothing aromatherapy bedroom spray to induce REM sleep and quiet overactive nighttime anxiety.",
    ingredients: ["Kashmir Lavender Oil", "Vetiver Hydrosol", "Clary Sage", "Distilled Water"],
    dosage: "Mist 2-3 pumps over pillow and bed linens 10 mins before sleep.",
    certifications: ["Non-Staining", "Natural Aromatics"]
  },
  {
    id: 54,
    name: "Ceramic Ultrasonic Aroma Diffuser & Humidifier",
    category: "aromatherapy",
    categoryLabel: "Aromatherapy & Dhoop",
    price: 1499,
    originalPrice: 1999,
    rating: 5.0,
    reviewCount: 74,
    dosha: "tridoshic",
    doshaLabel: "Home Harmony",
    benefits: ["Stress & Sleep"],
    organic: true,
    inStock: true,
    stockCount: 16,
    icon: "💨",
    image: "https://images.unsplash.com/photo-1546868871-7041f2a55e12?auto=format&fit=crop&w=600&q=80",
    description: "Handcrafted matte ceramic wellness diffuser with warm LED ambient breathing glow and auto shut-off.",
    ingredients: ["Ceramic Shell", "BPA-Free Reservoir", "Ultrasonic Transducer"],
    dosage: "Fill with 200ml water + 5 drops of essential oil.",
    certifications: ["1-Year Warranty", "Whisper Quiet (<20dB)"]
  },
  {
    id: 55,
    name: "Guggal & Loban Sambrani Dhoop Cups (Pack of 12)",
    category: "aromatherapy",
    categoryLabel: "Aromatherapy & Dhoop",
    price: 199,
    originalPrice: 250,
    rating: 4.8,
    reviewCount: 140,
    dosha: "kapha",
    doshaLabel: "Aura Cleansing",
    benefits: ["Stress & Sleep"],
    organic: true,
    inStock: true,
    stockCount: 80,
    icon: "🔥",
    image: "https://images.unsplash.com/photo-1506126613408-eca07ce68773?auto=format&fit=crop&w=600&q=80",
    description: "Cow dung base cups filled with natural Loban and Guggal resins to remove stagnant negative energies.",
    ingredients: ["Desi Cow Dung Shell", "Pure Benzoin (Loban)", "Commiphora Mukul (Guggal)"],
    dosage: "Light rim of cup, place on heat-safe holder.",
    certifications: ["100% Biodegradable", "Sacred Homa Herbs"]
  },
  {
    id: 56,
    name: "Rose & Cardamom Therapeutic Chakra Roll-On",
    category: "aromatherapy",
    categoryLabel: "Aromatherapy & Dhoop",
    price: 299,
    originalPrice: 380,
    rating: 4.8,
    reviewCount: 65,
    dosha: "pitta",
    doshaLabel: "Anahata Heart Chakra",
    benefits: ["Stress & Sleep", "Energy & Vitality"],
    organic: true,
    inStock: true,
    stockCount: 45,
    icon: "✨",
    image: "https://images.unsplash.com/photo-1608248597359-2ff96954b830?auto=format&fit=crop&w=600&q=80",
    description: "Portable pulse-point oil roll-on uplifting mood, grounding emotions, and opening heart space.",
    ingredients: ["Damask Rose Otto", "Green Cardamom Oil", "Jojoba Carrier Oil"],
    dosage: "Roll onto wrists, temples, and neck during moments of stress.",
    certifications: ["Pocket Sized", "Zero Synthetic Perfume"]
  },

  // =========================================================================
  // 8. YOGA, MEDITATION & COPPERWARE (6 Unique Products)
  // =========================================================================
  {
    id: 57,
    name: "Handcrafted Pure Copper Water Bottle (950ml)",
    category: "yoga-meditation",
    categoryLabel: "Yoga & Copperware",
    price: 899,
    originalPrice: 1199,
    rating: 4.9,
    reviewCount: 190,
    dosha: "tridoshic",
    doshaLabel: "Tamra Jal (All Doshas)",
    benefits: ["Digestion & Gut", "Immunity Boost"],
    organic: true,
    inStock: true,
    stockCount: 30,
    icon: "🫗",
    image: "https://images.unsplash.com/photo-1602143407151-7111542de6e8?auto=format&fit=crop&w=600&q=80",
    description: "99.6% pure hammered copper vessel to naturally alkalize water and infuse essential copper trace minerals.",
    ingredients: ["99.6% Certified Pure Copper Sheet"],
    dosage: "Store drinking water overnight (8 hours) and drink first thing in the morning.",
    certifications: ["Ayurvedic Tamra Jal", "Leak Proof Silicone Seal"]
  },
  {
    id: 58,
    name: "Organic Spelt & Buckwheat Yoga Zafu Cushion",
    category: "yoga-meditation",
    categoryLabel: "Yoga & Copperware",
    price: 1199,
    originalPrice: 1499,
    rating: 4.9,
    reviewCount: 63,
    dosha: "tridoshic",
    doshaLabel: "Tridoshic Comfort",
    benefits: ["Stress & Sleep"],
    organic: true,
    inStock: true,
    stockCount: 14,
    icon: "🪑",
    image: "https://images.unsplash.com/photo-1545205597-3d9d02c29597?auto=format&fit=crop&w=600&q=80",
    description: "Ergonomically contoured organic cotton cushion filled with triple-cleaned natural buckwheat hulls.",
    ingredients: ["100% Organic GOTS Cotton Canvas", "Natural Buckwheat Hulls"],
    dosage: "Sit cross-legged for optimal spinal alignment during Pranayama.",
    certifications: ["GOTS Certified Cotton", "Ergonomic Design"]
  },
  {
    id: 59,
    name: "Traditional Pure Copper Tongue Scraper",
    category: "yoga-meditation",
    categoryLabel: "Yoga & Copperware",
    price: 149,
    originalPrice: 199,
    rating: 4.9,
    reviewCount: 240,
    dosha: "tridoshic",
    doshaLabel: "Daily Dinacharya",
    benefits: ["Digestion & Gut"],
    organic: true,
    inStock: true,
    stockCount: 120,
    icon: "👅",
    image: "https://images.unsplash.com/photo-1544816155-12df9643f363?auto=format&fit=crop&w=600&q=80",
    description: "Essential Dinacharya tool to remove Ama (toxic metabolic coating), eliminate bad breath, and enhance taste buds.",
    ingredients: ["100% Solid Pure Copper"],
    dosage: "Gently scrape tongue 5-7 times back to front each morning.",
    certifications: ["Antibacterial Copper", "Smooth Rounded Edges"]
  },
  {
    id: 60,
    name: "Kansa Wand Face & Foot Bronze Massager",
    category: "yoga-meditation",
    categoryLabel: "Yoga & Copperware",
    price: 799,
    originalPrice: 999,
    rating: 4.9,
    reviewCount: 86,
    dosha: "pitta",
    doshaLabel: "Pitta Heat Detox",
    benefits: ["Skin Glow & Hair", "Stress & Sleep"],
    organic: true,
    inStock: true,
    stockCount: 22,
    icon: "🪄",
    image: "https://images.unsplash.com/photo-1512290900672-1f486240d425?auto=format&fit=crop&w=600&q=80",
    description: "Sacred bronze (Copper + Tin) wand handcrafted on teakwood to balance bodily pH and drain lymphatic tension.",
    ingredients: ["Pure Kansa Metal (Bronze)", "Seasoned Teakwood Handle"],
    dosage: "Apply facial oil or ghee and massage in figure-8 motions.",
    certifications: ["Ayurvedic Healing Metal", "Hand Carved"]
  },
  {
    id: 61,
    name: "Natural Organic Jute & Tree Rubber Yoga Mat",
    category: "yoga-meditation",
    categoryLabel: "Yoga & Copperware",
    price: 1699,
    originalPrice: 2199,
    rating: 5.0,
    reviewCount: 58,
    dosha: "vata",
    doshaLabel: "Vata Grounding Grip",
    benefits: ["Stress & Sleep", "Energy & Vitality"],
    organic: true,
    inStock: true,
    stockCount: 15,
    icon: "🧘",
    image: "https://images.unsplash.com/photo-1599447421416-3414500d18a5?auto=format&fit=crop&w=600&q=80",
    description: "Anti-slip eco-friendly mat made of unbleached golden jute fibers over biodegradable natural rubber cushioning.",
    ingredients: ["Natural Jute Fiber", "Sustainably Tapped Tree Rubber"],
    dosage: "Wipe with damp cloth after Asana practice.",
    certifications: ["100% Biodegradable", "PVC & Toxic Chemical Free"]
  },
  {
    id: 62,
    name: "Tibetan 7-Metal Sound Healing Singing Bowl",
    category: "yoga-meditation",
    categoryLabel: "Yoga & Copperware",
    price: 1299,
    originalPrice: 1650,
    rating: 4.8,
    reviewCount: 48,
    dosha: "tridoshic",
    doshaLabel: "Chakra Sound Resonance",
    benefits: ["Stress & Sleep"],
    organic: true,
    inStock: true,
    stockCount: 18,
    icon: "🔔",
    image: "https://images.unsplash.com/photo-1514432324607-a09d9b4aefdd?auto=format&fit=crop&w=600&q=80",
    description: "Hand-hammered bell metal singing bowl producing rich 432Hz harmonic vibrations to induce deep theta meditation.",
    ingredients: ["7-Metal Alloy (Copper, Tin, Zinc, Iron, Silver, etc.)", "Rosewood Mallet"],
    dosage: "Strike or circle rim with mallet during meditation.",
    certifications: ["432Hz Harmonic Tuned", "Hand Hammered"]
  },

  // =========================================================================
  // 9. PANCHAKARMA & WELLNESS GIFT SETS (4 Unique Products)
  // =========================================================================
  {
    id: 63,
    name: "Holistic 7-Day Ayurvedic Detox & Cleanse Kit",
    category: "wellness-kits",
    categoryLabel: "Panchakarma & Gift Sets",
    price: 1899,
    originalPrice: 2499,
    rating: 5.0,
    reviewCount: 47,
    dosha: "tridoshic",
    doshaLabel: "Tridoshic Reset",
    benefits: ["Digestion & Gut", "Immunity Boost", "Energy & Vitality"],
    organic: true,
    inStock: true,
    stockCount: 12,
    icon: "🎁",
    image: "https://images.unsplash.com/photo-1513519245088-0e12902e5a38?auto=format&fit=crop&w=600&q=80",
    description: "Complete curated Panchakarma home reset: Kitchari spice blend, Triphala detox, Copper tongue scraper, and Abhyanga oil.",
    ingredients: ["Kitchari Herbs", "Triphala", "Pure Sesame Oil", "Organic Spices"],
    dosage: "Follow the enclosed 7-day Ayurvedic routine guide.",
    certifications: ["Doctor Curated", "Comprehensive Kit"]
  },
  {
    id: 64,
    name: "Ayurvedic New Mother Postpartum Recovery Box",
    category: "wellness-kits",
    categoryLabel: "Panchakarma & Gift Sets",
    price: 2199,
    originalPrice: 2800,
    rating: 5.0,
    reviewCount: 38,
    dosha: "vata",
    doshaLabel: "Vata Restoration",
    benefits: ["Energy & Vitality", "Immunity Boost"],
    organic: true,
    inStock: true,
    stockCount: 10,
    icon: "👶",
    image: "https://images.unsplash.com/photo-1549465220-1a8b9238cd48?auto=format&fit=crop&w=600&q=80",
    description: "Traditional Sootika care package: Dashamoolarishta, Shatavari Granules, Dhanwantharam massage oil, and lactation tea.",
    ingredients: ["Dashamoola", "Shatavari Granules", "Bala Tailam", "Herbal Teas"],
    dosage: "Follow the daily trimester guidance card inside.",
    certifications: ["Vaidya Approved", "100% Natural"]
  },
  {
    id: 65,
    name: "Seasonal Immunity & Vata Shield Gift Hamper",
    category: "wellness-kits",
    categoryLabel: "Panchakarma & Gift Sets",
    price: 1499,
    originalPrice: 1899,
    rating: 4.9,
    reviewCount: 52,
    dosha: "vata",
    doshaLabel: "Vata Grounding Kit",
    benefits: ["Immunity Boost", "Stress & Sleep"],
    organic: true,
    inStock: true,
    stockCount: 16,
    icon: "📦",
    image: "https://images.unsplash.com/photo-1513201099705-a9746e1e201f?auto=format&fit=crop&w=600&q=80",
    description: "Curated winter and autumn wellness box with Chyawanprash, Golden Milk spice, Ashwagandha, and Nasya oil.",
    ingredients: ["Organic Chyawanprash", "Haldi Latte", "Ashwagandha", "Anu Tailam"],
    dosage: "Daily immunity protocol described in included wellness journal.",
    certifications: ["Eco Packed in Wood Box", "Festive Edition"]
  },
  {
    id: 66,
    name: "Ayurvedic Bridal Glow 21-Day Rituals Casket",
    category: "wellness-kits",
    categoryLabel: "Panchakarma & Gift Sets",
    price: 2499,
    originalPrice: 3200,
    rating: 5.0,
    reviewCount: 41,
    dosha: "pitta",
    doshaLabel: "Pitta Glow Ritual",
    benefits: ["Skin Glow & Hair"],
    organic: true,
    inStock: true,
    stockCount: 8,
    icon: "👰",
    image: "https://images.unsplash.com/photo-1522337360788-8b13dee7a37e?auto=format&fit=crop&w=600&q=80",
    description: "Imperial pre-wedding beauty hamper with Kumkumadi oil, Ubtan body polish, Damask Rose hydrosol, and Kansa wand.",
    ingredients: ["Kumkumadi Elixir", "Royal Ubtan", "Rose Mist", "Kansa Facial Wand"],
    dosage: "Follow the 21-day step-by-step beauty calendar.",
    certifications: ["Luxury Handmade", "Pure Saffron & Sandalwood"]
  }
];

// Helper search & filter methods
export const getProducts = async () => {
  const response = await fetch(`${API_BASE_URL}/api/products`);

  if (!response.ok) {
    throw new Error("Failed to fetch products");
  }

  const result = await response.json();

  return result.data;
};

export const getProductById = async (id) => {
  const response = await fetch(
    `${API_BASE_URL}/api/products/${id}`
  );

  if (!response.ok) {
    if (response.status === 404) {
      return null;
    }

    throw new Error("Failed to fetch product");
  }

  const result = await response.json();

  return result.data;
};

export const filterProducts = ({
  products = [],
  category = "all",
  dosha = "all",
  benefit = "",
  search = "",
  sortBy = "popular",
  inStockOnly = false,
  priceMax = 5000
}) => {
  return products.filter((product) => {
    // Category match
    if (category !== "all" && product.category !== category) {
      return false;
    }

    // Dosha match
    if (
      dosha !== "all" &&
      product.dosha !== dosha &&
      product.dosha !== "tridoshic"
    ) {
      return false;
    }

    // Benefit match
    if (benefit && !product.benefits?.includes(benefit)) {
      return false;
    }

    // In Stock filter
    if (inStockOnly && !product.inStock) {
      return false;
    }

    // Price range
    if (product.price > priceMax) {
      return false;
    }

    // Search query
    if (search.trim()) {
      const q = search.toLowerCase();

      const matchName =
        product.name?.toLowerCase().includes(q);

      const matchDesc =
        product.description?.toLowerCase().includes(q);

      const matchIngr =
        product.ingredients?.some((ing) =>
          ing.toLowerCase().includes(q)
        );

      const matchCat =
        product.categoryLabel?.toLowerCase().includes(q);

      if (!matchName && !matchDesc && !matchIngr && !matchCat) {
        return false;
      }
    }

    return true;
  }).sort((a, b) => {
    if (sortBy === "price-low") {
      return a.price - b.price;
    }

    if (sortBy === "price-high") {
      return b.price - a.price;
    }

    if (sortBy === "rating") {
      return (b.rating || 0) - (a.rating || 0);
    }

    return (b.reviewCount || 0) - (a.reviewCount || 0);
  });
};

export default productsData;